version: "3"
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE #suppresses some not useful error messages.
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=dev_db
      - MYSQL_ROOT_PASSWORD=password
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: dev_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
