version: "3"
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    networks:
      app-tier:
        aliases:
          - karolina.demo
    ports:
      - 80:80
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-tier
  mysql:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=dev_db
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - app-tier
#  selenium:
#    image: 'selenium/standalone-chrome-debug'
#    volumes:
#      - ./webroot:/data
#    ports:
#      - "4444:4444"
#      - "5900:5900"
#    privileged: true
#    networks:
#      app-tier:
#        aliases:
#          - selenium.demo

networks:
  app-tier:
    driver: bridge

volumes:
  mysqldata:
    driver: "local"